version: '3'

services:
    db:
        image: percona:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_USER: admin
            MYSQL_PASSWORD: pass
